name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Ensure repo exists
            cd ~
            if [ ! -d "docci-cd" ]; then
              git clone https://github.com/santhosh3007kumar/docci-cd.git
            else
              cd docci-cd
              git pull
            fi
            cd docci-cd
            # Pull latest images (v1 + SHA tag optional)
            docker pull "santhosh3007/frontend:v1"
            docker pull "santhosh3007/backend:v1"
            # Run containers
            docker compose -f docker-compose-deploy.yml up -d
            docker ps